// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaThuoc.Models;

#nullable disable

namespace QuanLyNhaThuoc.Migrations
{
    [DbContext(typeof(QL_NhaThuocContext))]
    partial class QL_NhaThuocContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyNhaThuoc.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCaLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCaLam"), 1L, 1);

                    b.Property<string>("GhiChuCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("GioNghiTrua")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.Property<DateTime?>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaCaLam")
                        .HasName("PK__CaLamVie__662C15A21D5C25D3");

                    b.ToTable("CaLamViec", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamCong"), 1L, 1);

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValueSql("(N'Không Đạt')");

                    b.Property<DateTime?>("ThoiGianRaVe")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianVaoLam")
                        .HasColumnType("datetime");

                    b.HasKey("MaChamCong", "MaNhanVien", "NgayChamCong")
                        .HasName("PK__ChamCong__307331A15F10C452");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"), 1L, 1);

                    b.Property<int>("DonHangMaDonHang")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThuocMaThuoc")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietD__CDF0A114F8C6B04F");

                    b.HasIndex("DonHangMaDonHang");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaThuoc");

                    b.HasIndex("ThuocMaThuoc");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChiTietPn", b =>
                {
                    b.Property<int>("MaChiTietPn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietPN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPn"), 1L, 1);

                    b.Property<decimal>("DonGiaXuat")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaTonKho")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietPn")
                        .HasName("PK__ChiTietP__651D0AF77C50A2D3");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaTonKho");

                    b.HasIndex(new[] { "MaThuoc", "MaPhieuNhap" }, "UQ_ChiTietPN_MaThuoc_MaPhieuNhap")
                        .IsUnique();

                    b.ToTable("ChiTietPN", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChiTietPx", b =>
                {
                    b.Property<int>("MaChiTietPx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietPX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPx"), 1L, 1);

                    b.Property<decimal>("DonGiaXuat")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaTonKho")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietPx")
                        .HasName("PK__ChiTietP__651D0AC186DEEEE9");

                    b.HasIndex("MaPhieuXuat");

                    b.HasIndex("MaTonKho");

                    b.HasIndex(new[] { "MaThuoc", "MaPhieuXuat" }, "UQ_ChiTietPX_MaThuoc_MaPhieuXuat")
                        .IsUnique();

                    b.ToTable("ChiTietPX", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"), 1L, 1);

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangMaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayDatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayGiaoHang")
                        .HasColumnType("date");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584AD8F05CCBB");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.DonHangKhachHangViewModels", b =>
                {
                    b.Property<string>("DiaChiDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DonHangKhachHangViewModels");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.Faq", b =>
                {
                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int");

                    b.Property<string>("CauHoiThuongGap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauTraLoiTuongUng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanhMucCauHoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhatCauHoi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTaoCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaCauHoi")
                        .HasName("PK__FAQ__1937D77BE483274F");

                    b.ToTable("FAQ", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"), 1L, 1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang__F5001DA348C369DB");

                    b.HasIndex("MaThuoc");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.HinhAnh", b =>
                {
                    b.Property<int>("MaHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinh"), 1L, 1);

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<string>("UrlAnh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHinh")
                        .HasName("PK__HinhAnh__13EE1084F53BE805");

                    b.HasIndex("MaThuoc");

                    b.ToTable("HinhAnh", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E5FB3D1819");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoaiSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiSanPham"), 1L, 1);

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLoaiSanPham")
                        .HasName("PK__LoaiSanP__ECCF699F0BD2FA30");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"), 1L, 1);

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("LuongThang")
                        .HasColumnType("date");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("KhauTru")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("LuongThucNhan")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("LuongThuong")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("NgayTraLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoCaLamViec")
                        .HasColumnType("int");

                    b.HasKey("MaLuong", "MaNhanVien", "LuongThang")
                        .HasName("PK__Luong__6609A48DBF719780");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D7625E27EED9");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"), 1L, 1);

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LuongCoBan1Ca")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("LuongTangCa1Gio")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaCaLamViec")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTuyenDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA472CF2237E");

                    b.HasIndex("MaCaLamViec");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhanQuyen", b =>
                {
                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int");

                    b.HasIndex("MaQuyen");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PhieuNha__1470EF3B36F3F0AA");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex(new[] { "MaPhieuNhap" }, "UQ_PhieuNhap_MaPhieuNhap")
                        .IsUnique();

                    b.ToTable("PhieuNhap", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuXuat"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiNhan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaPhieuXuat")
                        .HasName("PK__PhieuXua__26C4B5A2917AC412");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex(new[] { "MaPhieuXuat" }, "UQ_PhieuXuat_MaPhieuXuat")
                        .IsUnique();

                    b.ToTable("PhieuXuat", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.QuyenTruyCap", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"), 1L, 1);

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__QuyenTru__1D4B7ED44F6F0300");

                    b.ToTable("QuyenTruyCap", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.SaoLuuVaPhucHoi", b =>
                {
                    b.Property<int>("MaSaoLuu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSaoLuu"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("TenFileSaoLuu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ThoiGianPhucHoi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianSaoLuu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThaiSaoLuu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSaoLuu")
                        .HasName("PK__SaoLuuVa__7ABE083C2FC08E21");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("SaoLuuVaPhucHoi", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaQr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MaQR");

                    b.Property<DateTime?>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__ThanhToa__D4B25844E6E7518F");

                    b.HasIndex("MaDonHang");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuoc"), 1L, 1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<int?>("MaLoaiSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThuoc")
                        .HasName("PK__Thuoc__4BB1F6201849222A");

                    b.HasIndex("MaLoaiSanPham");

                    b.HasIndex(new[] { "MaThuoc" }, "UQ_Thuoc_MaThuoc")
                        .IsUnique();

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.TonKho", b =>
                {
                    b.Property<int>("MaTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTonKho"), 1L, 1);

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGioCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoLuongCanhBao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTonKho")
                        .HasName("PK__TonKho__2D970FAA48FBE53C");

                    b.HasIndex("MaThuoc");

                    b.ToTable("TonKho", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.UpdateDonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UpdateDonHangs");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"), 1L, 1);

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__C24C41CFB0D1B022");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChamCong", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK_ChamCong_NhanVien");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangMaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaThuoc.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDonHang_MaDonHang");

                    b.HasOne("QuanLyNhaThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDonHang_MaThuoc");

                    b.HasOne("QuanLyNhaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("ThuocMaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaThuocNavigation");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChiTietPn", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.PhieuNhap", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPns")
                        .HasForeignKey("MaPhieuNhap")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPN_MaPhieuNhap");

                    b.HasOne("QuanLyNhaThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietPns")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPN_MaThuoc");

                    b.HasOne("QuanLyNhaThuoc.Models.TonKho", "MaTonKhoNavigation")
                        .WithMany("ChiTietPns")
                        .HasForeignKey("MaTonKho")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPN_MaTonKho");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaThuocNavigation");

                    b.Navigation("MaTonKhoNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ChiTietPx", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.PhieuXuat", "MaPhieuXuatNavigation")
                        .WithMany("ChiTietPxes")
                        .HasForeignKey("MaPhieuXuat")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPX_MaPhieuXuat");

                    b.HasOne("QuanLyNhaThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietPxes")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPX_MaThuoc");

                    b.HasOne("QuanLyNhaThuoc.Models.TonKho", "MaTonKhoNavigation")
                        .WithMany("ChiTietPxes")
                        .HasForeignKey("MaTonKho")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPX_MaTonKho");

                    b.Navigation("MaPhieuXuatNavigation");

                    b.Navigation("MaThuocNavigation");

                    b.Navigation("MaTonKhoNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.DonHang", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaThuoc.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_KhachHang");

                    b.HasOne("QuanLyNhaThuoc.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_MaNhanVien");

                    b.Navigation("KhachHang");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.GioHang", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_MaThuoc");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.HinhAnh", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaThuoc")
                        .HasConstraintName("FK_HinhAnh_MaThuoc");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK_KhachHang_MaNguoiDung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.LoaiSanPham", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK_MaDanhMuc");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.Luong", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK_Luong_MaNhanVien");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDung_MaVaiTro");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.CaLamViec", "MaCaLamViecNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCaLamViec")
                        .IsRequired()
                        .HasConstraintName("FK_NhanVien_MaCaLamViec");

                    b.HasOne("QuanLyNhaThuoc.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK_NhanVien_MaNguoiDung");

                    b.Navigation("MaCaLamViecNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhanQuyen", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.QuyenTruyCap", "MaQuyenNavigation")
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .HasConstraintName("FK_PhanQuyen_Quyen");

                    b.HasOne("QuanLyNhaThuoc.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .HasConstraintName("FK_PhanQuyen_VaiTro");

                    b.Navigation("MaQuyenNavigation");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK_PhieuNhap_MaNhanVien");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK_PhieuXuat_MaNhanVien");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.SaoLuuVaPhucHoi", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("SaoLuuVaPhucHois")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK_SaoLuuVaPhucHoi_MaNhanVien");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToan_MaDonHang");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.Thuoc", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.LoaiSanPham", "MaLoaiSanPhamNavigation")
                        .WithMany("Thuocs")
                        .HasForeignKey("MaLoaiSanPham")
                        .HasConstraintName("FK_Thuoc_MaLoaiSanPham");

                    b.Navigation("MaLoaiSanPhamNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.TonKho", b =>
                {
                    b.HasOne("QuanLyNhaThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("TonKhos")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_TonKho_MaThuoc");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.CaLamViec", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.DanhMuc", b =>
                {
                    b.Navigation("LoaiSanPhams");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.LoaiSanPham", b =>
                {
                    b.Navigation("Thuocs");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.NguoiDung", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.NhanVien", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("DonHangs");

                    b.Navigation("Luongs");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");

                    b.Navigation("SaoLuuVaPhucHois");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPns");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPxes");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietPns");

                    b.Navigation("ChiTietPxes");

                    b.Navigation("GioHangs");

                    b.Navigation("HinhAnhs");

                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.TonKho", b =>
                {
                    b.Navigation("ChiTietPns");

                    b.Navigation("ChiTietPxes");
                });

            modelBuilder.Entity("QuanLyNhaThuoc.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
